export const CPU_PROFILER_DEFAULT_SAMPLE_INTERVAL = 10;
export const CPU_PROFILER_MIN_SAMPLE_INTERVAL = 1;
export const CPU_PROFILER_MAX_SAMPLE_INTERVAL = 100;
export const CPU_PROFILER_DEFAULT_HISTORY_LIMIT = 120;
export const CPU_PROFILER_MIN_HISTORY_LIMIT = 10;
export const CPU_PROFILER_MAX_HISTORY_LIMIT = 1000;
