export const HUB_TARGET_COMPOUNDS: ResourceConstant[] = [
  RESOURCE_CATALYZED_UTRIUM_ACID, // XUH2O
  RESOURCE_CATALYZED_UTRIUM_ALKALIDE, // XUHO2
  RESOURCE_CATALYZED_KEANIUM_ACID, // XKH2O
  RESOURCE_CATALYZED_KEANIUM_ALKALIDE, // XKHO2
  RESOURCE_CATALYZED_LEMERGIUM_ACID, // XLH2O
  RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE, // XLHO2
  RESOURCE_CATALYZED_ZYNTHIUM_ACID, // XZH2O
  RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE, // XZHO2
  RESOURCE_CATALYZED_GHODIUM_ACID, // XGH2O
  RESOURCE_CATALYZED_GHODIUM_ALKALIDE, // XGHO2
];

export const HUB_PLAN_INTERVAL = 50;
export const HUB_RESERVE_PER_ROOM = 5000;
export const HUB_RESERVE_PER_COMPOUND = 20_000;
export const HUB_STORAGE_PAUSE_FREE_CAPACITY = 100_000;
export const HUB_SURPLUS_THRESHOLD = HUB_RESERVE_PER_ROOM + 500;
export const HUB_INTERNAL_ONLY = true;
export const HUB_DISTRIBUTED_STORAGE = true;
