'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const S=require('./loader-test-support.cjs'),H=S.H,G=require('../../scripts/build-treasury-compat-loader.cjs'),N=G.N;
const marks=['parentStart','callStart','bodyStart','bodyEnd','callEnd','parentEnd'];
const get=()=>H.load('treasuryCompatCpu.ts');
const old=()=>fs.readFileSync(path.join(__dirname,'fixtures/reader-before-boundary-attribution-xiii.ts.txt'),'utf8');
const live=()=>fs.readFileSync(H.file('treasuryCompatRead.ts'),'utf8');
const xiii=()=>fs.readFileSync(path.join(__dirname,'fixtures/reader-before-task-hotpath-xiv.ts.txt'),'utf8');
const reports=s=>s.lines.map(x=>JSON.parse(x)).filter(x=>x.kind==='treasury-legacy-read-bridge');
function scene(setup=()=>{},trace=true,safety=true){const s=S.make();s.cfg={...s.cfg,startTick:100,endTick:400};s.step=.001;setup(s);s.observer=s.api.createTreasuryCompatPreview(s.cfg,s.ports,{cpuDiagnostics:true,commitmentBoundaryDiagnostics:trace,localSafetyStop:safety});return s;}
function envelope(s){return reports(s).at(-1).cpuProfile.commitmentEnvelope;}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function fakeAccounting(){const a=get().createCompatCpuAccounting(100,100,1,true);a.invoked('readerLoad');a.invoked('observationBuild');a.checkpoint(101,'commitmentBuild');a.commitmentMark('callStart',102);a.invoked('commitmentBuild');a.attributionBoundary(120,'commitmentSetup');a.attributionBoundary(121,'commitmentTasks');a.attributionBoundary(122,'commitmentReservations');a.attributionBoundary(123,'commitmentFinalize');a.attributionBoundary(124);a.commitmentMark('callEnd',125);a.checkpoint(126,'report');return a;}
test('XIII exact reversible transform and public IX-to-live chain',()=>{assert.equal(N.transform(old()),xiii());assert.equal(N.restore(xiii()),old());const ix=fs.readFileSync(path.join(H.ROOT,G.PREVIEW_FIXTURE),'utf8');assert.equal(G.P.transform(ix),live());assert.equal(G.P.restore(live()),ix);assert.throws(()=>N.transform(old().replace('const memory = ports.memory();','const memory=ports.memory();')),/BOUNDARY_XIII_TRANSFORM_COUNT/);});
test('XIII six marks close parent, call and measured body without subtracting overhead',()=>{const p=fakeAccounting().snapshot('beforeSerialization'),m=p.commitmentEnvelope.marks;assert.equal(p.commitmentEnvelope.status,'complete');assert.deepEqual(H.json(m),{parentStart:1,callStart:2,bodyStart:20,bodyEnd:24,callEnd:25,parentEnd:26});near(m.parentEnd-m.parentStart,p.phases.commitmentBuild);near(m.bodyEnd-m.bodyStart,Object.values(p.attribution.intervals).reduce((n,x)=>n+x,0));near(m.bodyStart-m.callStart,18);});
test('XIII call-not-made is distinct from zero cost',()=>{const a=get().createCompatCpuAccounting(0,100,1,true);a.checkpoint(.2,'commitmentBuild');a.checkpoint(.3,'report');const p=a.snapshot('beforeSerialization');assert.equal(p.calls.commitmentBuild,0);assert.equal(p.commitmentEnvelope.status,'not_called');assert.equal(p.commitmentEnvelope.marks.callStart,undefined);near(p.phases.commitmentBuild,.1);});
test('XIII missing inner marks are incomplete rather than synthesized',()=>{const a=get().createCompatCpuAccounting(0,100,1,true);a.checkpoint(.1,'commitmentBuild');a.commitmentMark('callStart',.2);a.invoked('commitmentBuild');a.commitmentMark('callEnd',.3);a.checkpoint(.4,'report');assert.equal(a.snapshot('beforeSerialization').commitmentEnvelope.status,'incomplete');});
test('XIII duplicate and regressed envelope boundaries fail closed',()=>{const a=get().createCompatCpuAccounting(0,100,1,true);a.checkpoint(.1,'commitmentBuild');a.commitmentMark('callStart',.2);assert.throws(()=>a.commitmentMark('callStart',.3));const b=get().createCompatCpuAccounting(0,100,1,true);b.checkpoint(.4,'commitmentBuild');assert.throws(()=>b.commitmentMark('callStart',.3));});
test('XIII non-finite envelope boundary is rejected',()=>{for(const v of [NaN,Infinity,-1]){const a=get().createCompatCpuAccounting(0,100,1,true);a.checkpoint(.1,'commitmentBuild');assert.throws(()=>a.commitmentMark('callStart',v));}});
test('XIII snapshots are immutable and tail does not repeat envelope',()=>{const a=fakeAccounting(),p=a.snapshot('beforeSerialization');assert.ok(Object.isFrozen(p.commitmentEnvelope));assert.ok(Object.isFrozen(p.commitmentEnvelope.marks));assert.equal(a.snapshot('afterRetention').commitmentEnvelope,undefined);const b=get().createCompatCpuAccounting(0,200,2,true);assert.equal(b.snapshot('fault').commitmentEnvelope.marks.callStart,undefined);});
test('XIII real full builder has complete trace and 4 projection rows',()=>{const s=scene();s.observer.run();const r=reports(s)[0],e=envelope(s);assert.equal(e.status,'complete');assert.deepEqual(Object.keys(e.marks),marks);assert.equal(r.commitments.rows.length,4);assert.equal(r.cpuProfile.attribution.boundaries,12);assert.equal(r.cpuProfile.attribution.work.projectionIndexQueries,16);near(e.marks.parentEnd-e.marks.parentStart,r.cpuProfile.phases.commitmentBuild);near(e.marks.bodyEnd-e.marks.bodyStart,['commitmentSetup','commitmentTasks','commitmentReservations','commitmentFinalize'].reduce((n,k)=>n+r.cpuProfile.attribution.intervals[k],0));});
for(const count of [0,14,256])test('XIII constant added probes with '+count+' tasks and reservations',()=>{const setup=s=>{for(let i=0;i<count;i++){s.memory.data.resourceControl.tasks[i]=S.task({id:'t'+i});s.memory.runtime.resourceReservations[i]=S.reservation();}};const a=scene(setup,false,false),b=scene(setup,true,false);a.observer.run();b.observer.run();assert.equal(b.calls.cpu-a.calls.cpu,2);assert.equal(envelope(b).status,'complete');assert.equal(reports(b)[0].cpuProfile.attribution.work.commitmentTaskRecords,count);assert.equal(reports(b)[0].cpuProfile.attribution.work.commitmentReservationRecords,count);});
test('XIII call-entry injection stays outside body, and stops later samples',()=>{const s=scene(s=>{const base=s.ports.readers;s.ports.readers=()=>{const r=base();return {...r,buildCommitments(o){s.cpuValue+=19;return r.buildCommitments(o);}};};});s.observer.run();const e=envelope(s);assert.ok(e.marks.bodyStart-e.marks.callStart>=19);assert.ok(e.marks.bodyEnd-e.marks.bodyStart<1);assert.equal(s.observer.stats().safetyStopped,true);assert.equal(s.lines.filter(x=>JSON.parse(x).kind==='treasury-compat-safety-stop').length,1);const before=JSON.stringify(s.calls),logs=s.lines.length;s.game.time=200;s.observer.run();assert.equal(JSON.stringify(s.calls),before);assert.equal(s.lines.length,logs);});
test('XIII body injection is inside measured body, not relabeled as entry',()=>{const s=scene(s=>{const base=s.ports.readers;s.ports.readers=()=>{const r=base();return {...r,buildCommitments(o){const d=o.compatDiagnostics;return r.buildCommitments({...o,compatDiagnostics:{...d,boundary(n){if(n==='commitmentTasks')s.cpuValue+=19;d.boundary(n);}}});}};};});s.observer.run();const e=envelope(s);assert.ok(e.marks.bodyEnd-e.marks.bodyStart>=19);assert.ok(e.marks.bodyStart-e.marks.callStart<1);});
test('XIII call-return injection stays outside measured body',()=>{const s=scene(s=>{const base=s.ports.readers;s.ports.readers=()=>{const r=base();return {...r,buildCommitments(o){const x=r.buildCommitments(o);s.cpuValue+=19;return x;}};};});s.observer.run();const e=envelope(s);assert.ok(e.marks.callEnd-e.marks.bodyEnd>=19);assert.ok(e.marks.bodyEnd-e.marks.bodyStart<1);});
test('XIII tail overrun latches even when emitted prefix was below five',()=>{const s=scene(s=>{s.emitCost=6;});s.observer.run();assert.ok(reports(s)[0].cpuBeforeSerializationAndEmit<2);assert.equal(s.observer.stats().safetyStopped,true);const calls=H.json(s.calls);s.game.time=200;s.observer.run();assert.deepEqual(s.calls,calls);});
test('XIII notification exception cannot clear the latch or escape',()=>{const s=scene(s=>{const emit=s.ports.emit;s.ports.emit=line=>{if(JSON.parse(line).kind==='treasury-compat-safety-stop')throw new Error('test log failed');emit(line);};s.emitCost=6;});assert.doesNotThrow(()=>s.observer.run());assert.equal(s.observer.stats().safetyStopped,true);s.game.time=200;assert.equal(s.observer.run().status,'disabled_after_safety_stop');});
test('XIII reset after first due tick cannot re-arm a later sample',()=>{const s=scene(s=>{s.game.time=200;});assert.equal(s.observer.run().status,'disabled_after_safety_stop');assert.equal(s.calls.memory,0);assert.equal(s.calls.cpu,0);assert.equal(s.calls.readers,0);assert.equal(s.observer.stats().safetyReason,'WINDOW_RESTART_UNPROVEN');});
test('XIII first due CPU admission skipped cannot silently shift the window',()=>{const s=scene(s=>{s.bucket=0;});assert.equal(s.observer.run().status,'cpu_skipped');s.bucket=9000;s.game.time=200;assert.equal(s.observer.run().status,'disabled_after_safety_stop');assert.equal(s.calls.readers,0);});
test('XIII OFF does not touch any port',()=>{const s=scene(s=>{s.cfg={...s.cfg,enabled:false};});s.observer.run();assert.equal(Object.values(s.calls).reduce((n,v)=>n+v,0),0);assert.equal(s.lines.length,0);});
test('XIII no extra probes when builder never called',()=>{const f=s=>{s.memory.data.resourceControl.tasks=null;};const a=scene(f,false,false),b=scene(f,true,false);a.observer.run();b.observer.run();assert.equal(a.calls.cpu,b.calls.cpu);assert.equal(envelope(b).status,'not_called');
 const t=scene(x=>{let count=0;const port=x.ports.cpu;x.ports.cpu=()=>{count++;if(count===17)x.cpuValue+=2.1;return port();};});
 t.observer.run();assert.equal(reports(t)[0].cpuProfile.calls.commitmentBuild,0);assert.equal(reports(t)[0].status,'partial_cpu_budget');
});
test('XIII measurement fault disables preview and cannot escape old bot',()=>{const s=scene(s=>{let n=0;s.ports.cpu=()=>({used:++n>3?NaN:.1,tickLimit:100,bucket:9000});});assert.doesNotThrow(()=>s.observer.run());assert.equal(s.observer.stats().fault,true);assert.equal(s.observer.run().status,'disabled_after_fault');});
for(const name of Object.keys(S.scenarios))test('XIII business parity and no writes: '+name,()=>{const a=S.make(),b=S.make();a.api=S.readerApi(old());S.scenarios[name](a);S.scenarios[name](b);a.observer=a.api.createTreasuryCompatPreview(a.cfg,a.ports);b.observer=b.api.createTreasuryCompatPreview(b.cfg,b.ports);const ga={writes:0},gb={writes:0};a.memory=H.guard(a.memory,ga);b.memory=H.guard(b.memory,gb);for(let i=1;i<=4;i++){a.game.time=b.game.time=i*100;a.cpuValue=b.cpuValue=.1;a.observer.run();b.observer.run();}assert.equal(JSON.stringify(a.lines),JSON.stringify(b.lines));assert.deepEqual([ga.writes,gb.writes],[0,0]);});
test('XIII historical runtime retains its original latch; FC1 explicitly owns native admission',()=>{
 const historical=fs.readFileSync(path.join(__dirname,'fixtures/runtime-before-full-cost-fc1.ts.txt'),'utf8');
 assert.equal(G.blob(Buffer.from(historical)),'13e8e356784da1c606e9c1cc8fccdaaa8d436b0c');
 assert.match(historical,/commitmentBoundaryDiagnostics: true/);assert.match(historical,/localSafetyStop: true/);
 const current=fs.readFileSync(H.file('treasuryCompatRuntime.ts'),'utf8');
 assert.match(current,/commitmentBoundaryDiagnostics: true/);assert.match(current,/localSafetyStop: false/);
 assert.match(current,/admissionHeadroomCpu: 55/);assert.match(current,/CPU_OBSERVED_EXPOSURE_STOP/);
 assert.match(fs.readFileSync(H.file('treasuryCompatConfig.ts'),'utf8'),/enabled: false/);
});
