'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),crypto=require('node:crypto');
const S=require('./loader-test-support.cjs'),H=S.H,fs=S.fs,path=S.path,ts=S.ts;
const G=require('../../scripts/build-treasury-compat-loader.cjs'),B=require('./build-test-support.cjs');
const read=n=>fs.readFileSync(H.file(n),'utf8');
const old=n=>fs.readFileSync(path.join(__dirname,'fixtures/'+n+'-before-read-envelope-xv.ts.txt'),'utf8');
const liveCore=()=>read('treasuryCompatReadCore.generated.ts'),liveReader=()=>read('treasuryCompatRead.ts');
const sha=t=>crypto.createHash('sha256').update(t).digest('hex');
function cpuApi(text){const c=vm.createContext({exports:{}});vm.runInContext(ts.transpileModule(text,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2019}}).outputText,c);return c.exports;}
const beforeCpu=cpuApi(old('cpu')),afterCpu=cpuApi(read('treasuryCompatCpu.ts'));
function pair(setup=()=>{},diagnostics=false){const a=S.make(old('core'),diagnostics),b=S.make(liveCore(),diagnostics);a.api=S.readerApi(old('reader'));for(const s of [a,b]){setup(s);const writes={writes:0};s.memory=H.guard(s.memory,writes);s.writes=writes;s.observer=s.api.createTreasuryCompatPreview(s.cfg,s.ports,{cpuDiagnostics:diagnostics,commitmentBoundaryDiagnostics:diagnostics,taskBoundaryDiagnostics:diagnostics,localSafetyStop:diagnostics});}for(let n=1;n<=4;n++){for(const s of [a,b]){s.game.time=n*100;s.cpuValue=.1;s.observer.run();}}assert.deepEqual(a.lines,b.lines);assert.deepEqual(H.json(a.observer.stats()),H.json(b.observer.stats()));assert.equal(a.writes.writes,0);assert.equal(b.writes.writes,0);assert.deepEqual(a.calls,b.calls);return {a,b};}
test('XV historical fixtures authenticate exact accepted XIV bytes',()=>{assert.equal(sha(old('reader')),'75438e82c4b891fea5debe55d92d8de400252758d7b7e26139608eceab0f2e4e');assert.equal(sha(old('cpu')),'e95f80f679d7f36987294d6f8049c2f6987959fc9b95302289b66d27d0e44c1a');assert.equal(sha(old('core')),'8eab90fbf64c47da27cf665aa5b13c0f4a18410af17690a81c132275c58904c6');});
test('XV current generation and exact inverses retain every historical stage',()=>{for(const[n,f,inv,file]of [['reader',G.V.previewTransform,G.V.previewRestore,'treasuryCompatRead.ts'],['cpu',G.V.cpuTransform,G.V.cpuRestore,'treasuryCompatCpu.ts'],['core',G.V.coreTransform,G.V.coreRestore,'treasuryCompatReadCore.generated.ts']]){assert.equal(f(old(n)),read(file));assert.equal(inv(read(file)),old(n));assert.throws(()=>f(old(n)+old(n)),/READ_ENVELOPE_XV_TRANSFORM_COUNT/);assert.throws(()=>inv('shifted'),/READ_ENVELOPE_XV_TRANSFORM_COUNT/);}const ix=fs.readFileSync(path.join(H.ROOT,G.PREVIEW_FIXTURE),'utf8');assert.equal(G.P.transform(ix),liveReader());assert.equal(G.P.restore(liveReader()),ix);});
const reader=S.readerApi(liveReader()),oldReader=S.readerApi(old('reader'));
for(const[name,text]of Object.entries({empty:'',ascii:'ASCII\n\t\0"\\'.repeat(2000),bmp:'中文héllø'.repeat(100),astral:'😀𐐀'.repeat(500),loneHigh:'\ud800x\udbff',loneLow:'\udc00\udfff',mixed:'head\ud800\udc00\ud800tail中文',json:JSON.stringify({id:'中文😀\ud800',resource:'H',values:Array(100).fill(123)})}))test('XV exact UTF-8 size and historical equality: '+name,()=>{assert.equal(reader.compatUtf8Bytes(text),Buffer.byteLength(text));assert.equal(reader.compatUtf8Bytes(text),oldReader.compatUtf8Bytes(text));});
test('XV UTF-8 deterministic random UTF-16 differential corpus preserves lone surrogates',()=>{let seed=13;for(let n=0;n<256;n++){let s='';for(let j=0;j<n%127;j++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;s+=String.fromCharCode(seed>>>16);}assert.equal(reader.compatUtf8Bytes(s),Buffer.byteLength(s));assert.equal(reader.compatUtf8Bytes(s),oldReader.compatUtf8Bytes(s));}});
test('XV ASCII path invokes no JS per-character loop; Unicode executes unchanged fallback',()=>{function count(text,input){const ctx=vm.createContext({exports:{},require:k=>H.load('treasuryCompatCpu.ts')});vm.runInContext('globalThis.charReads=0; const old=String.prototype.charCodeAt; String.prototype.charCodeAt=function(i){charReads++;return old.call(this,i);};'+ts.transpileModule(text,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2019}}).outputText,ctx);return {bytes:ctx.exports.compatUtf8Bytes(input),count:ctx.charReads};}const text='x'.repeat(8192);assert.deepEqual(count(old('reader'),text),{bytes:8192,count:8192});assert.deepEqual(count(liveReader(),text),{bytes:8192,count:0});assert.deepEqual(count(liveReader(),'x中😀'),count(old('reader'),'x中😀'));});
for(const name of Object.keys(S.scenarios))test('XV all diagnostic fields byte-parity, CPU port calls and no Memory writes: '+name,()=>pair(S.scenarios[name],true));
for(const mode of ['inherited-accessor','own-accessor','nonenumerable','symbol','null-prototype','257-own'])test('XV full table own-data boundary preserved: '+mode,()=>pair(s=>{let table={t:S.task()};if(mode==='inherited-accessor')Object.setPrototypeOf(table,Object.defineProperty({},'evil',{enumerable:true,get(){throw Error('inherited getter invoked');}}));if(mode==='own-accessor')Object.defineProperty(table,'bad',{enumerable:true,get(){throw Error('own getter invoked');}});if(mode==='nonenumerable')Object.defineProperty(table,'hidden',{enumerable:false,value:S.task()});if(mode==='symbol')table[Symbol('hidden')]=S.task();if(mode==='null-prototype')table=Object.assign(Object.create(null),table);if(mode==='257-own')for(let n=0;n<257;n++)table[n]=S.task({id:'t'+n});s.memory.data.resourceControl.tasks=table;},true));
test('XV removes exactly one redundant own-membership dispatch per enumerable table item',()=>{function measure(text){const apiText=text.replace('const own = (x: Rec, k: string) => Object.prototype.hasOwnProperty.call(x, k);','const own = (x: Rec, k: string) => { globalThis.__ownCalls++; return Object.prototype.hasOwnProperty.call(x, k); };');const s=S.make(liveCore(),false);const c=vm.createContext({exports:{},__ownCalls:0,require:k=>H.load('treasuryCompatCpu.ts')});vm.runInContext(ts.transpileModule(apiText,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2019}}).outputText,c);for(let n=0;n<54;n++)s.memory.data.resourceControl.tasks[n]=S.task({id:'t'+n});for(let n=0;n<12;n++)s.memory.runtime.resourceReservations[n]=S.reservation({holderId:'h'+n});const p=c.exports.createTreasuryCompatPreview(s.cfg,s.ports);p.run();return {calls:c.__ownCalls,line:s.lines[0]};}const a=measure(old('reader')),b=measure(liveReader());assert.equal(a.line,b.line);assert.equal(a.calls-b.calls,66);});
test('XV observation query memo allocates only on first query, preserves frozen cache identity and sample isolation',()=>{function run(text){const s=S.make(text,false);let allocations=0;const marked=text.replace('let roomResourcesCache;','let roomResourcesCache;').replace('roomResourcesCache = new Map();','roomResourcesCache = (globalThis.__mapAllocations++, new Map());');const c=vm.createContext({exports:{},__mapAllocations:0,Game:s.game,Memory:s.memory,RESOURCES_ALL:s.resources});vm.runInContext(ts.transpileModule(marked,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2019}}).outputText,c);const r=c.exports.createCompatibilityReadCore();const o=r.buildObservation({scope:'market-fresh',epochSeq:1,rooms:Object.values(s.game.rooms)});allocations=c.__mapAllocations;const first=o.roomResources('W1N1');assert.ok(Object.isFrozen(first));assert.equal(o.roomResources('W1N1'),first);o.roomResources('__proto__');assert.equal(c.__mapAllocations,1);const other=r.buildObservation({scope:'market-fresh',epochSeq:2,rooms:Object.values(s.game.rooms)});assert.notEqual(other.roomResources('W1N1'),first);assert.equal(c.__mapAllocations,2);return {allocations,data:H.json(o.data),first:H.json(first)};}const a=run(old('core')),b=run(liveCore());assert.equal(a.allocations,1);assert.equal(b.allocations,0);assert.deepEqual(a.data,b.data);assert.deepEqual(a.first,b.first);});
test('XV full index API remains equivalent on mixed, overflow and nonempty reservation corpus',()=>{for(let seed=1;seed<=16;seed++){const corpus=B.deterministicCorpus(seed,seed%2?57:256);const a=S.make(old('core'),false),b=S.make(liveCore(),false);for(const s of [a,b]){s.memory.data.resourceControl.tasks=H.json(corpus.tasks);s.memory.runtime.resourceReservations=H.json(corpus.reservations);s.game.time=300+seed;}assert.deepEqual(B.snapshot(S.build(a)),B.snapshot(S.build(b)));}});
function both(actions){let results=[];for(const api of [beforeCpu,afterCpu]){const a=api.createCompatCpuAccounting(0,100,1,true,true),out=[];for(const [f,...args]of actions){try{a[f](...args);out.push({ok:true});}catch(e){out.push({error:e.message});}out.push(H.json(a.snapshot('fault')));}results.push(out);}assert.deepEqual(results[1],results[0]);}
test('XV accounting membership retains strict unknown-key rejection, prefix partial updates and getter evaluation order',()=>{const values={observationRooms:2};Object.defineProperty(values,'bad',{enumerable:true,get(){return 1;}});both([['attributionWork',values],['checkpoint',.1,'directRead'],['checkpoint',.2,'__proto__'],['checkpoint',.2,'toString'],['attributionBoundary',.3,'toString'],['invoked','constructor'],['attributionWork',{observationRooms:Number.MAX_SAFE_INTEGER}],['attributionWork',{observationRooms:1}],['attributionWork',{}]]);});
test('XV work snapshots distinguish absent keys from measured zero without allocating a key list',()=>{both([['attributionWork',{}],['attributionWork',{observationRooms:0}],['attributionWork',{observationRooms:2}],['attributionWork',{observationExistingLocations:-1}],['attributionWork',{observationExistingLocations:0}]]);});
test('XV CPU start values and runtime null-next compatibility remain identical',()=>{for(const n of [NaN,Infinity,-1,0,.25])for(const api of [beforeCpu,afterCpu]){if(!Number.isFinite(n)||n<0)assert.throws(()=>api.createCompatCpuAccounting(n,100,1));else assert.doesNotThrow(()=>api.createCompatCpuAccounting(n,100,1));}both([['checkpoint',.1,null],['checkpoint',.2,undefined],['checkpoint',.3,'commitmentBuild'],['invoked','commitmentBuild'],['commitmentMark','callStart',.4],['attributionBoundary',.5,'commitmentSetup'],['attributionBoundary',.6,'commitmentTasks'],['taskMark','firstPendingStart',.7,1],['taskMark','firstPendingEnd',.8,1],['attributionBoundary',.9,'commitmentReservations'],['attributionBoundary',1,'commitmentFinalize'],['attributionBoundary',1.1],['commitmentMark','callEnd',1.2],['checkpoint',1.3,'report']]);});
test('XV snapshot copies and tail-only completion remain immutable and unlinked',()=>{for(const api of [beforeCpu,afterCpu]){const a=api.createCompatCpuAccounting(0,100,1,true,true);a.attributionWork({observationRooms:0});const p=a.snapshot('beforeSerialization');a.attributionWork({observationRooms:2});assert.equal(p.attribution.work.observationRooms,0);assert.ok(Object.isFrozen(p));assert.ok(Object.isFrozen(p.attribution.work));a.checkpoint(.1,'serializationAndSize');a.checkpoint(.2,'emit');a.checkpoint(.3,'retention');a.checkpoint(.4);const tail=a.snapshot('afterRetention');assert.equal(tail.completion,'tail_only');assert.equal(tail.attribution,undefined);assert.equal(tail.commitmentEnvelope,undefined);assert.equal(tail.taskEnvelope,undefined);}});
test('XV CPU observations, full report schema and output-limit decisions are not reduced',()=>{for(const maxLogBytes of [1024,4096,16384])pair(s=>{s.cfg={...s.cfg,maxLogBytes};s.memory.data.resourceControl.tasks={t:S.task()};s.game.rooms.W1N1.storage.id='多字节😀'.repeat(8);},true);});
