'use strict';
const {test}=require('node:test'), assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const S=require('./loader-test-support.cjs'),H=S.H,B=require('./build-test-support.cjs'),G=require('../../scripts/build-treasury-compat-loader.cjs');
const beforeCore=()=>fs.readFileSync(path.join(__dirname,'fixtures/core-before-task-hotpath-xiv.ts.txt'),'utf8');
const beforeReader=()=>fs.readFileSync(path.join(__dirname,'fixtures/reader-before-task-hotpath-xiv.ts.txt'),'utf8');
const liveCore=()=>fs.readFileSync(H.file('treasuryCompatReadCore.generated.ts'),'utf8');
const liveReader=()=>fs.readFileSync(H.file('treasuryCompatRead.ts'),'utf8');
const reports=s=>s.lines.map(JSON.parse).filter(r=>r.kind==='treasury-legacy-read-bridge');
function scene(setup=()=>{},enabled=true){const s=S.make();s.cfg={...s.cfg,startTick:100,endTick:400};s.step=.001;setup(s);s.observer=s.api.createTreasuryCompatPreview(s.cfg,s.ports,{cpuDiagnostics:true,commitmentBoundaryDiagnostics:true,localSafetyStop:true,taskBoundaryDiagnostics:enabled});return s;}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function oldNew(setup){const a=S.make(beforeCore(),false),b=S.make(liveCore(),false);a.api=S.readerApi(beforeReader());setup(a);setup(b);const ga={writes:0},gb={writes:0};a.memory=H.guard(a.memory,ga);b.memory=H.guard(b.memory,gb);a.observer=a.api.createTreasuryCompatPreview(a.cfg,a.ports);b.observer=b.api.createTreasuryCompatPreview(b.cfg,b.ports);for(let k=1;k<=4;k++){a.game.time=b.game.time=100*k;a.observer.run();b.observer.run();}assert.deepEqual(a.lines,b.lines);assert.equal(ga.writes+gb.writes,0);return {a,b};}
test('XIV exact core/preview inverses, including current public H and P chains',()=>{assert.equal(G.T.coreTransform(beforeCore()),G.V.coreRestore(liveCore()));assert.equal(G.T.coreRestore(G.V.coreRestore(liveCore())),beforeCore());assert.equal(G.T.previewTransform(beforeReader()),G.V.previewRestore(liveReader()));assert.equal(G.T.previewRestore(G.V.previewRestore(liveReader())),beforeReader());const ix=fs.readFileSync(path.join(__dirname,'fixtures/core-before-hotpath-optimization-xi.ts.txt'),'utf8');assert.equal(G.H.transform(ix),liveCore());assert.equal(G.H.restore(liveCore()),ix);});
test('XIV authenticates the XIII fixtures instead of inventing historical expected output',()=>{assert.equal(crypto.createHash('sha256').update(beforeCore()).digest('hex'),'3bd42eee815562492a440bef2f0e2879707dba1bd61a78eb15083fe3ef2fc92c');assert.equal(crypto.createHash('sha256').update(beforeReader()).digest('hex'),'9da241f859211d90d529118fe8d84437f6feee69aff17d318b2f941a60261098');});
test('XIV changed and doubled transform anchors are rejected',()=>{assert.throws(()=>G.T.coreTransform(beforeCore().replace('metrics.taskRecords = taskIds.length;','metrics.taskRecords = 0;')),/TASK_XIV_TRANSFORM_COUNT/);assert.throws(()=>G.T.previewTransform(beforeReader()+beforeReader()),/TASK_XIV_TRANSFORM_COUNT/);});
for(const name of Object.keys(S.scenarios))test('XIV complete report parity and no writes: '+name,()=>oldNew(S.scenarios[name]));
test('XIV full index API matches XIII for seeded mixed, damaged and overflowing corpora',()=>{for(let seed=1;seed<=24;seed++){const corpus=B.deterministicCorpus(seed,seed%2?6:256);const a=S.make(beforeCore(),false),b=S.make(liveCore(),false);for(const s of [a,b]){s.memory.data.resourceControl.tasks=H.json(corpus.tasks);s.memory.runtime.resourceReservations=H.json(corpus.reservations);s.game.time=5000+seed;}assert.deepEqual(B.snapshot(S.build(a)),B.snapshot(S.build(b)),'seed '+seed);}});
test('XIV zero remaining, self routes, key aliases and first-route id behavior are preserved',()=>{const setup=s=>{s.memory.data.resourceControl.tasks={a:S.task({id:undefined,fromRoomName:'__proto__',toRoomName:'__proto__',remainingAmount:0}),b:S.task({id:'second',fromRoomName:'__proto__',toRoomName:'__proto__',remainingAmount:0}),c:S.task({fromRoomName:'W1N1\0H',toRoomName:'W1N1\0H',amount:Number.MAX_SAFE_INTEGER,remainingAmount:Number.MAX_SAFE_INTEGER}),d:S.task({amount:Number.MAX_SAFE_INTEGER,remainingAmount:Number.MAX_SAFE_INTEGER}),e:S.task({amount:Number.MAX_SAFE_INTEGER,remainingAmount:Number.MAX_SAFE_INTEGER})};};const a=S.make(beforeCore(),false),b=S.make(liveCore(),false);setup(a);setup(b);assert.deepEqual(B.snapshot(S.build(a)),B.snapshot(S.build(b)));});
function additions(text,count){const s=S.make(text,false);const marked='globalThis.__xivAdds=0;\n'+text.replace('function addSafeInteger(current, addend) {','function addSafeInteger(current, addend) { globalThis.__xivAdds++;')+'\nexport const readXivAdds=()=>globalThis.__xivAdds;';s.core=S.capsule(marked,s);for(let n=0;n<count;n++)s.memory.data.resourceControl.tasks[n]=S.task({id:'t'+n});const result=S.build(s);return {count:s.core.readXivAdds(),snapshot:B.snapshot(result)};}
test('XIV removes four checked-add helper invocations per ordinary pending task without removing arithmetic guards',()=>{for(const n of [1,6,256]){const a=additions(beforeCore(),n),b=additions(liveCore(),n);assert.equal(a.count,4*n);assert.equal(b.count,0);assert.deepEqual(a.snapshot,b.snapshot);}});
function descriptors(text){const s=S.make(liveCore(),false);s.api=S.readerApi(text);s.memory.runtime.resourceControl={updatedAt:100,rooms:{W1N1:{},W2N1:{}}};const counts={},seen=new WeakMap();function track(value,p='Memory'){if(!value||typeof value!=='object')return value;if(seen.has(value))return seen.get(value);const x=new Proxy(value,{get:(t,k)=>track(Reflect.get(t,k),p+'.'+String(k)),getOwnPropertyDescriptor(t,k){const key=p+'.'+String(k);counts[key]=(counts[key]||0)+1;const d=Reflect.getOwnPropertyDescriptor(t,k);return d&&'value'in d&&d.configurable?{...d,value:track(d.value,key)}:d;}});seen.set(value,x);return x;}s.memory=track(s.memory);s.observer=s.api.createTreasuryCompatPreview(s.cfg,s.ports);s.observer.run();return {counts,line:s.lines[0]};}
test('XIV projection root descriptor lookups reduce from repeated endpoint reads to one sample cursor',()=>{const a=descriptors(beforeReader()),b=descriptors(liveReader());assert.equal(a.line,b.line);assert.equal(a.counts['Memory.runtime'],10);assert.equal(b.counts['Memory.runtime'],1);assert.equal(a.counts['Memory.runtime.resourceControl'],8);assert.equal(b.counts['Memory.runtime.resourceControl'],1);});
test('XIV cursor does not survive into the next sample or replace independent Store reads',()=>{const s=scene(()=>{},false);s.observer.run();s.memory.runtime.resourceControl={updatedAt:200,rooms:{W1N1:{storageUsedCapacity:0,storageFreeCapacity:0,storageEnergy:0}}};s.game.time=200;s.observer.run();const r=reports(s)[1];assert.equal(r.endpoints[0].legacyProjection.status,'mismatch');assert.equal(s.calls.observation,2);assert.equal(s.calls.memory,2);});
for(const mutate of ['inherited','accessor','null','array','nonenumerable'])test('XIV own-data projection boundary: '+mutate,()=>oldNew(s=>{if(mutate==='inherited')Object.setPrototypeOf(s.memory.runtime,{resourceControl:{updatedAt:100,rooms:{}}});else if(mutate==='accessor')Object.defineProperty(s.memory.runtime,'resourceControl',{configurable:true,get(){throw Error('must not call');}});else if(mutate==='nonenumerable')Object.defineProperty(s.memory.runtime,'resourceControl',{configurable:true,value:{updatedAt:100,rooms:{}}});else s.memory.runtime.resourceControl=mutate==='null'?null:[];}));
for(const count of [0,1,6,256])test('XIV probe count is bounded per table: '+count,()=>{const setup=s=>{for(let i=0;i<count;i++){s.memory.data.resourceControl.tasks[i]=S.task({id:'t'+i});s.memory.runtime.resourceReservations[i]=S.reservation();}};const a=scene(setup,false),b=scene(setup,true);a.observer.run();b.observer.run();assert.equal(b.calls.cpu-a.calls.cpu,count?2:0);const p=reports(b)[0].cpuProfile,t=p.taskEnvelope;assert.equal(t.status,count?'complete':'no_pending');if(count){const m=t.marks;near(m.tasksEnd-m.tasksStart,p.attribution.intervals.commitmentTasks);assert.equal(t.firstPendingOrdinal,1);}assert.equal(p.attribution.work.commitmentTaskRecords,count);assert.equal(p.attribution.work.commitmentReservationRecords,count);});
test('XIV not-called carries no invented task or task timing',()=>{const s=scene(s=>{s.memory.data.resourceControl.tasks=null;});s.observer.run();const p=reports(s)[0].cpuProfile;assert.equal(p.taskEnvelope.status,'not_called');assert.equal(p.taskEnvelope.firstPendingOrdinal,null);assert.deepEqual(H.json(p.taskEnvelope.marks),{});});
test('XIV nonpending/damaged prefix selects first valid pending ordinal, not task zero',()=>{const s=scene(s=>{s.memory.data.resourceControl.tasks={a:S.task({status:'done'}),b:S.task({amount:-1}),c:S.task({id:'first-valid'}),d:S.task()};});s.observer.run();const p=reports(s)[0].cpuProfile;assert.equal(p.taskEnvelope.status,'complete');assert.equal(p.taskEnvelope.firstPendingOrdinal,3);assert.equal(p.attribution.work.commitmentTaskRecords,4);});
test('XIV later overflow still scans the whole table and cannot drop first-region end',()=>{const s=scene(s=>{s.memory.data.resourceControl.tasks={a:S.task({amount:Number.MAX_SAFE_INTEGER,remainingAmount:Number.MAX_SAFE_INTEGER}),b:S.task({amount:1,remainingAmount:1}),c:S.task({status:'done'})};});s.observer.run();const p=reports(s)[0].cpuProfile;assert.equal(p.taskEnvelope.status,'complete');assert.equal(p.attribution.work.commitmentTaskRecords,3);assert.ok(p.attribution.work.commitmentTaskInvalidEvents>0);});
test('XIV pending processing throw closes first region then disables preview, never skips the fault',()=>{const s=scene(s=>{const t=S.task();Object.defineProperty(t,'reason',{get(){throw Error('task reason fault');}});s.memory.data.resourceControl.tasks={t};});assert.doesNotThrow(()=>s.observer.run());assert.equal(s.observer.stats().fault,true);});
test('XIV inner latency is assigned to selected first-pending interval and latches subsequent samples',()=>{const s=scene(s=>{s.memory.data.resourceControl.tasks={t:S.task()};const readers=s.ports.readers;s.ports.readers=()=>{const r=readers();return {...r,buildCommitments(o){const d=o.compatDiagnostics;return r.buildCommitments({...o,compatDiagnostics:{...d,taskBoundary(mark,n){if(mark==='firstPendingEnd')s.cpuValue+=14;d.taskBoundary(mark,n);}}});}};};});s.observer.run();const r=reports(s)[0],m=r.cpuProfile.taskEnvelope.marks;assert.ok(m.firstPendingEnd-m.firstPendingStart>=14);assert.ok(m.firstPendingStart-m.tasksStart<1);assert.equal(r.localSafety.latched,true);const count=s.calls.cpu;s.game.time=200;s.observer.run();assert.equal(s.calls.cpu,count);});
test('XIV latency before selected task is not mislabeled as pending aggregation',()=>{const s=scene(s=>{const t=S.task();let fired=false;Object.defineProperty(t,'status',{get(){if(!fired){s.cpuValue+=14;fired=true;}return 'pending';}});s.memory.data.resourceControl.tasks={t};});s.observer.run();const m=reports(s)[0].cpuProfile.taskEnvelope.marks;assert.ok(m.firstPendingStart-m.tasksStart>=14);assert.ok(m.firstPendingEnd-m.firstPendingStart<1);});
test('XIV task profiles are frozen, fresh per sample and absent from tail-only completion',()=>{const s=scene(s=>{s.memory.data.resourceControl.tasks={t:S.task()};});s.observer.run();const first=reports(s)[0];s.game.time=200;s.observer.run();assert.equal(reports(s)[1].previousCpuProfile.taskEnvelope,undefined);assert.equal(first.cpuProfile.taskEnvelope.firstPendingOrdinal,1);const a=H.load('treasuryCompatCpu.ts').createCompatCpuAccounting(0,100,1,true,true);const p=a.snapshot('fault');assert.ok(Object.isFrozen(p.taskEnvelope));assert.ok(Object.isFrozen(p.taskEnvelope.marks));});
test('XIV task marker rejects regression, duplicate, invalid ordinal and inconsistent ordinal',()=>{const factory=()=>H.load('treasuryCompatCpu.ts').createCompatCpuAccounting(0,100,1,true,true);for(const n of [0,-1,257,1.5,NaN]){const a=factory();a.attributionBoundary(.1,'commitmentTasks');assert.throws(()=>a.taskMark('firstPendingStart',.2,n));}const a=factory();a.attributionBoundary(.1,'commitmentTasks');a.taskMark('firstPendingStart',.2,2);assert.throws(()=>a.taskMark('firstPendingStart',.3,2));assert.throws(()=>a.taskMark('firstPendingEnd',.3,3));assert.throws(()=>a.taskMark('firstPendingEnd',.1,2));});
test('XIV marker pair is opt-in: historical XIII probe behavior and schema are retained',()=>{const s=scene(s=>{s.memory.data.resourceControl.tasks={t:S.task()};},false);s.observer.run();const r=reports(s)[0];assert.equal(r.diagnosticRevision,'XIII');assert.equal(r.cpuProfile.taskEnvelope,undefined);});
